# Generated by Django 5.2 on 2025-04-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTM', '0002_remove_task_user_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
