# Generated by Django 5.2 on 2025-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTM', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
